Tag range to create changelog
requarks/changelog-action pull request #6
Opened 2022-06-27 05:05 UTC by sitepark-veltrup

In my case I would like to create changelogs not only for the last release but also for hotfixes further back in time.

```mermaid
%%{init: { 'gitGraph': {'showCommitLabel': false}} }%%
    gitGraph
       commit tag:"1.0.0"
       commit tag:"1.1.0"
       branch hotfix/1.1.x order:2
       checkout main
       commit tag:"..."
       commit tag:"2.0.0"
       commit tag:"2.1.0"
       branch hotfix/2.1.x order:1
       commit tag:"2.1.1"
       commit tag:"2.1.2"
       commit tag:"..."
       checkout hotfix/1.1.x
       commit tag:"1.1.1"
       commit tag:"1.1.2"
       commit tag:"..."
       checkout main
       commit tag:"..."
```

Here it would help me if instead of a tag, I could specify a range over which the changelog is generated.

I still determine the necessary tag area for me about an extra script.

I use it like this:
``` yaml
name: Create GitHub Release Draft

on:
  push:
    tags:
      - [0-9]+.[0-9]+.[0-9]+

jobs:
  release-draft-with-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previousTag
        run: |
          name=$(git --no-pager tag --sort=-v:refname --merged ${{ github.ref_name }} | sed -n 2,2p)
          name=${name:=$(git rev-list --max-parents=0 HEAD)}
          echo "previousTag: $name"
          echo "::set-output name=name::$name"

      - name: Update CHANGELOG
        id: changelog
        uses: sitepark-com/changelog-action@main
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ steps.previousTag.outputs.name }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
```

2022-10-11 07:34 UTC, tmetzke commented
@NGPixel, any chance we can see this merged anytime soon? 🙂

2022-10-12 03:44 UTC, NGPixel requested changes

2022-10-12 03:44 UTC, NGPixel commented on CHANGELOG.md
> +## [v1.4.0] - 2022-06-21
Don't modify the CHANGELOG file, it's generated automatically by github actions.

2022-10-13 10:52 UTC, tmetzke commented on CHANGELOG.md
> +
```suggestion
```

2022-10-13 10:53 UTC, tmetzke commented on CHANGELOG.md
> +[v1.4.0]: https://github.com/sitepark-com/changelog-action/compare/v1.3.2...v1.4.0
```suggestion
[v1.3.2]: https://github.com/requarks/changelog-action/compare/v1.3.1...v1.3.2
```

2022-10-18 23:06 UTC, matheusdavidson commented
This is a great addition to support prereleases and hotfixes

2022-10-18 23:42 UTC, matheusdavidson commented
@sitepark-veltrup not sure it's only on my end but CHANGELOG.md file doesn't get updated anymore, the output is good and going with the new release tho.

2022-10-18 23:45 UTC, matheusdavidson commented
@sitepark-veltrup this is the action log:
![image](https://user-images.githubusercontent.com/2229994/196565357-407b7cfa-be57-4a63-9f9b-665c5ba7c156.png)

2022-10-19 08:58 UTC, sitepark-veltrup commented
> @sitepark-veltrup not sure it's only on my end but CHANGELOG.md file doesn't get updated anymore, the output is good and going with the new release tho.

I myself don't use the feature to write the CHANGELOG.md but only use it to create Github release drafts. Therefore I don't have a test scenario.

But I think I found the reason and committed a fix.

2022-11-10 01:18 UTC, josiahwitheford commented
This looks awesome. Any chance it's likely to be merged soon?

Cheers,
Joey

2022-11-15 01:02 UTC, merged